### ISSUE TITLE
WP-Property not compaticble with latest WP update

### ISSUE THREAD

**Issue by Becca800** [wp-property/wp-property#619]
Several people are having new issues with the latest WP update and WP-Property not working.
For me, pagination is not working again. SHowing jquery issues related to WP-Property.

**Comment by abrobins** [comment]
I'm dealing with the same pagination issue so I'm having to stay on WordPress 5.5.3 and even that occasionally is having some pagination issues.

**Comment by Roberto-1960** [comment]
I have the same problem after the last update to wordpress 5.6, the WP-Property 2.4.1 plugin and the WP Avalon 1.1.0 theme do not work correctly as regards Propety-overview and Property Search.

**Comment by SoSeductive** [comment]
@Becca800  @abrobins @Roberto-1960 
Hello everyone. We’ve made some fixes to WP Property and now we’re going to test it. You can help us and update your WP Property from our `develop` branch. Can you do this and provide feedback, have your problems been fixed?

We also made some minor fixes to the WP Avalon theme.

[WP Property (develop)](https://github.com/wp-property/wp-property/tree/develop-den)
[WP Avalon (develop)](https://github.com/wp-property/wp-avalon/tree/develop-den)

**Comment by Becca800** [comment]
Sure thing and thanks. I'll let you know when I've updated and had a look around. Thanks!

**Comment by Becca800** [comment]
@SoSeductive The pagination still doesn't work. I get a Prev and Next link that now shows but the links don't work. Prior to the WP update, the old pagination showed the pages (1,2, 3 etc) and worked beautifully.
How it looks now (with the dev plugin):

![prevnext](https://user-images.githubusercontent.com/31107558/106328814-7253d580-624e-11eb-9813-d1557c5f9e33.jpg)

How it used to look before the WP update (and it worked)

![usedto](https://user-images.githubusercontent.com/31107558/106328859-839ce200-624e-11eb-9a6e-fc628b4ca242.jpg)

**Comment by Becca800** [comment]
My search is working as it should.

**Comment by Becca800** [comment]
My property overview works fine as well but I use a custom template I created.

**Comment by SoSeductive** [comment]
@Becca800 I can't replicate your issue with pagination. Can you give a link to page with this issue and explain which shortcode you use for show property overview page?

**Comment by Becca800** [comment]
@SoSeductive Strangely, the previous next buttons are working now and there is a very new look about the pagination but it works
example: https://kwrealtybigisland.com/properties/our-listings/
Which means I must have had a cache issue at the time.
Shortcode used for this page is [property_overview officeid=2894 sorter_on sort_by=price sort_order=DESC]

**Comment by SoSeductive** [comment]
@Becca800 Probably yes, it could be cache. If you want to use different pagination type, you can change it with your shortcode. For use this pagination type, which you showed, you should add `pagination_type= numeric`. 
![image](https://user-images.githubusercontent.com/2156026/106499077-cc5fcf80-64c8-11eb-848a-8219881bed06.png)
Also, in new version we added `pagination_type=loadmore`. Please, read documentation https://wp-property.github.io/docs/shortcode_cheatsheet/#gsc.tab=0 and changes in new `WP Property`

**Comment by abrobins** [comment]
Hi guys, @Becca800 & @SoSeductive I just wanted to point out that I just went to: https://kwrealtybigisland.com/properties/68-1015-pauoa-wy-kamuela-hi-96743/ 

And tried to click through the images in the slideshow for the listing and they're not working. This is exactly the issue I'm having on my client's site. Are you running a developer version on that site where that issue should be fixed? I just wanted to point out that I've never been to your site so I should have no cache on my computer and I still am having issues with the pagination on the individual listing pages. 

Thanks!
Blair

**Comment by Becca800** [comment]
@abrobins @SoSeductive You're right. Slideshow isn't working - strange. I didn't notice that before.

**Comment by SoSeductive** [comment]
@Becca800 @abrobins If you check firebug you can see JS error not from our plugins. Fix this issues and slideshow will works

**Comment by Becca800** [comment]
@SoSeductive My console shows these errors (in Chrome), some with the slider:

jquery.min.js:2 jQuery.Deferred exception: $ is not a function TypeError: $ is not a function
    at HTMLDocument.<anonymous> (https://kwrealtybigisland.com/properties/68-1015-pauoa-wy-kamuela-hi-96743/:196:3)
    at HTMLDocument.dispatch (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:43090)
    at HTMLDocument.v.handle (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:41074)
    at Object.trigger (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:71513)
    at s.fn.init.triggerHandler (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:72192)
    at HTMLDocument.<anonymous> (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery-migrate.min.js:2:8598)
    at e (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:30005)
    at t (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 jQuery.Deferred exception: Cannot create property 'guid' on string '.swiper-slide' TypeError: Cannot create property 'guid' on string '.swiper-slide'
    at Object.add (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:40905)
    at Object.s.event.add (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery-migrate.min.js:2:7886)
    at HTMLDivElement.<anonymous> (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:40138)
    at Function.each (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:2976)
    at s.fn.init.each (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:1454)
    at ke (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:40114)
    at s.fn.init.on (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:46741)
    at HTMLDivElement.<anonymous> (https://kwrealtybigisland.com/wp-content/plugins/wp-property/addons/wp-property-responsive-slideshow/static/scripts/res-slideshow.js?ver=5.6:84:53)
    at Function.each (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:2976)
    at s.fn.init.each (https://c0.wp.com/c/5.6/wp-includes/js/jquery/jquery.min.js:2:1454) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: $ is not a function
    at HTMLDocument.<anonymous> ((index):196)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.v.handle (jquery.min.js:2)
    at Object.trigger (jquery.min.js:2)
    at s.fn.init.triggerHandler (jquery.min.js:2)
    at HTMLDocument.<anonymous> (jquery-migrate.min.js:2)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)
jquery.min.js:2 Uncaught TypeError: Cannot create property 'guid' on string '.swiper-slide'
    at Object.add (jquery.min.js:2)
    at Object.s.event.add (jquery-migrate.min.js:2)
    at HTMLDivElement.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at s.fn.init.each (jquery.min.js:2)
    at ke (jquery.min.js:2)
    at s.fn.init.on (jquery.min.js:2)
    at HTMLDivElement.<anonymous> (res-slideshow.js?ver=5.6:84)
    at Function.each (jquery.min.js:2)
    at s.fn.init.each (jquery.min.js:2)
res-slideshow.js?ver=5.6:82 Uncaught TypeError: enDisKeyCtrl is not a function
    at Array.<anonymous> (res-slideshow.js?ver=5.6:82)
    at Swiper.s.emit (swiper.jquery.js?ver=5.6:2618)
    at Swiper.s.onTransitionStart (swiper.jquery.js?ver=5.6:1889)
    at Swiper.s.slideTo (swiper.jquery.js?ver=5.6:1857)
    at Swiper.s.slideNext (swiper.jquery.js?ver=5.6:1929)
    at HTMLDivElement.Swiper.s.onClickNext (swiper.jquery.js?ver=5.6:1199)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)

**Comment by Becca800** [comment]
@SoSeductive I disabled all plugins in troubleshooting mode except for wp-property (the new dev version) and the slideshow still doesn't work.

**Comment by NessSEO** [comment]
Probably not a long term solution but since the WordPress update caused functionality problems with WP-Property I implimented the jQuery Manager for WordPress plugin and it has resolved the problems. If the issue is affecting a client website it's a solution to get things working again.

**Comment by Becca800** [comment]
Thanks @NessSEO - what did you set the jquery version to in the manager?  Edit - if I roll back the jquery to 2.2.4.min.js - the slideshow works again. Thanks!

**Comment by NessSEO** [comment]
I have jQuery Settings set to jquery-1.12.4.js and jQuery Migrate Settings set to jquery-migrate-1.4.1.min.js

**Comment by markheydon** [comment]
> I have jQuery Settings set to jquery-1.12.4.js and jQuery Migrate Settings set to jquery-migrate-1.4.1.min.js

Same here, that 'fixed' sliders not working on property pages for my client site too.

**Comment by SoSeductive** [comment]
@NessSEO @markheydon @Becca800 @abrobins I made some changes in WP Property and WP Avalon theme. Now WPP Responsive Slideshow should work. Please, check it
[WP Property (develop)](https://github.com/wp-property/wp-property/archive/develop-den.zip)
[WP Avalon (develop)](https://github.com/wp-property/wp-avalon/archive/develop-den.zip)

**Comment by planv** [comment]
Fixed in new release - https://github.com/wp-property/wp-property/releases/tag/2.4.2
Closing the ticket.

**Comment by abrobins** [comment]
@Becca800 are you guys still seeing an issue with this? I am still on WordPress 5.5.3 because if I upgrade to the latest version of WP my slideshow doesn't work?

**Comment by Becca800** [comment]
@abrobins I use this shortcode in my template and it works:
[property_responsive_slideshow slider_width=100%]
You have to first make sure the responsive slideshow is enabled in properties > addons.
